### ISSUE TITLE
Guidelines for Model Driven Standards (MDS)

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/conceptual-modeling-group#5]
A number of SWGs are looking to identify guidelines for Model Driven Standards (MDS).

[Testbed-17](https://docs.ogc.org/per/21-035r1.html) conducted research on the topic and identified [criteria](https://docs.ogc.org/per/21-035r1.html#toc28) for applying model driven architecture to standards.

The Conceptual Modeling group is invited to identify requirements and/or recommendations that should feature in an MDS Guidelines document that is focused on Conceptual Modeling.

Please post your suggestion in this thread and indicate whether you are suggesting a Requirement or a Recommendation. 

We recommend having a look at [OGC 21-035r1](https://docs.ogc.org/per/21-035r1.html), for some additional background.

This GitHub Issue will be closed on February 28th, 2023.

**Comment by lvdbrink** [comment]
Could the deadline be extended? I saw this only this week at the OGC meeting.

**Comment by sgrellet** [comment]
+1 on @lvdbrink request

**Comment by KathiSchleidt** [comment]
In addition, it would be most valuable to have some more detailed information on @rob-metalinkage 's Building Blocks

@ghobona are you aware of any information not hidden on Rob's laptop on this?

**Comment by lvdbrink** [comment]
A few suggestions from me after partly reading the ER. Who has time to read these long documents.... 

- Recommendation: include a clear definition of the concept of "conceptual model". In the related ER [OGC 21-035r1](https://docs.ogc.org/per/21-035r1.html) this is defined as 

> model that defines concepts of a universe of discourse.

But defines 2.1.7. platform-independent model as 

> conceptual model ([Clause 2.1.2](https://docs.ogc.org/per/21-035r1.html#term-conceptual-model)) that does not contain platform-specific concerns

This seems very strange to me. Are there then also conceptual models that do contain platform-specific concerns? I would not agree with such a model being conceptual. 

- Recommendation about tooling. Do not require the use of specific tooling, but recommend them. The ER claims that metanorma and shapechange are the best options, but has no mention of other tools that were considered. 
- Requirement: SVG diagrams (there is an EA [plugin](https://community.sparxsystems.com/community-resources/706-svg-diagram-export-add-in) )
- Write clear recommendations about cross references to classes in other models. 
- Recommend a best practice for JSON encoding rules (a proposal for this can be found [here](https://github.com/geonovum/uml2json)). 
- Require a standardized metamodel (ISO 19109 based) and implement validation against this metamodel in the MDA tool.

**Comment by ghobona** [comment]
@KathiSchleidt 

The recording of the presentation by @rob-metalinkage to the OGC-NA at the 125th OGC Member Meeting is [here](https://portal.ogc.org/index.php?m=projects&a=view&project_id=82&tab=2&artifact_id=103410).

The recording of the presentation by @rob-metalinkage during the Today's Innovations, Tomorrow's Technologies & Future Directions at the 125th OGC Member Meeting is [here](https://portal.ogc.org/index.php?m=projects&a=view&project_id=82&tab=2&artifact_id=103582).

The recording of the Important Things discussion briefed by @ingosimonis and @ogcscotts is [here](https://portal.ogc.org/files/?artifact_id=104110).

Recording of the presentation during the OGC API SWGs session is [here](https://portal.ogc.org/files/?artifact_id=104208).

Access to all of the recordings is password-protected.

**Comment by ghobona** [comment]
@lvdbrink Thanks for the feedback. 

I agree, typically conceptual models do not contain platform-specific concerns.

Regarding the EA SVG plug-in, I was not aware of it. The plug-in is worth looking into in a future initiative.

**Comment by heidivanparys** [comment]
Regarding EA and SVG: EA 16.1 supports saving diagrams as SVG from version 16.1 and onwards. See

* https://www.sparxsystems.com/products/ea/history.html
* https://sparxsystems.com/products/ea/16.1/#747FAF7E-FFB1-4994-95B0-BCFA53DFDA95

So far only manual export to SVG is supported, as far as I can see, at least I couldn't make automated export work for SVG. See also https://www.sparxsystems.com/enterprise_architect_user_guide/16.1/add-ins___scripting/project_2.html:

> Type: Long - the file type
>      -  If type = 0 then it is a metafile
>      -  If type = 1 then it uses the file type from the name extension
>         (that is, .bmp, .jpg, .gif, .png, .tga)

```
project.PutDiagramImageToFile(project.GUIDtoXML(currentDiagram.DiagramGUID), fileName, 1);
```

I tried just changing the filename to a name ending on .svg, and/or changing the type to 0, but none of that worked, the created file wasn't valid. If anyone knows how to do this, as an undocumented feature perhaps, please let me know! @ronaldtse, @jechterhoff

I sent a feature request to Sparx. If more people want this: the more people send a feature request, the higher the chances this will be supported in the near future 🙂.

**Comment by ghobona** [comment]
Everyone, thanks for the feedback.

**Comment by ronaldtse** [comment]
Thank you @heidivanparys , EA 16.1 now offers bulk SVG exports and I can verify that.

That said, the SVG exports are often contain layout overlapping issues compared to the PNG. There's still work for them to do.

### EA PNG
![ea-exported-image-png](https://user-images.githubusercontent.com/11865/228803639-95b826c8-33a1-4e78-a387-935242220ca5.png)

### EA SVG
![ea-exported-image-svg](https://user-images.githubusercontent.com/11865/228803598-76fa6b19-0ff3-44f5-908e-42b8e8c99de6.svg)
